---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: portainer

labels:
  - pairs:
      app: portainer
    includeSelectors: true

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - pvc.yaml
  - portainer-deployment.yaml
  - portainer-service.yaml
